---

namespace: junipernetworks

name: eda

version: 1.1.13

readme: README.md

authors:
  - Andrew Block <andy.block@gmail.com>
  - Edwin Jacques <ejacques@juniper.net>

description: Ansible Event Driven Automation

license_file: 'LICENSE'

tags:
  - kubernetes
  - k8s
  - cloud
  - infrastructure
  - eda
  - junipernetworks

dependencies: {}

repository: https://github.com/Juniper/k8s.eda

documentation: https://github.com/Juniper/k8s.eda

issues: https://github.com/Juniper/k8s.eda/issues

build_ignore:
  - .github
  - .venv
  - .git
  - .python-version
  - .gitignore
  - Makefile
  - Pipfile*
  - junipernetworks-*.tar.gz
  - .eda-collection
  - .pre-commit-config.yaml
  - .vscode
  - pytest.ini
  - conftest.py
  - .pytest-kind
  - .pytest_cache
  - plugins/.pytest_cache
  - plugins/event_source/test_k8s.py
  - test-bin
