---

- name: Listen for ConfigMaps across
  hosts: all
  sources:
    - junipernetworks.eda.k8s:
        api_version: v1
        kind: ConfigMap
  rules:
    - name: Print Add Events
      condition: event.type == "ADDED"
      action:
        debug:
